### ISSUE TITLE
Github-token missing error

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/connector-runtime-docker#22]
__Describe the Bug__

Automatic **Add issue to poject** github action fails with following error:

`Error: Input required and not supplied: github-token`

Logs:
[Add issue to project](https://github.com/camunda/connector-runtime-docker/actions/runs/4165098724/jobs/7207847127#logs)

__Steps to Reproduce__

1. create a PR

__Expected Behavior__

Every action should run successfully.

__Environment__

Not applicable.

**Comment by bastiankoerber** [comment]
@markfarkas-camunda can i assign it to you and move it to ready?

**Comment by markfarkas-camunda** [comment]
The reason it was failing: Github token was missing. I added the specific Github token secret, which solved the issue. Add issue to project action is working now. See: https://github.com/camunda/connector-runtime-docker/actions/runs/4283796535
